spring:
  application:
    name: zuul-server
server:
  port: 8762
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
management:
  endpoints:
    web:
      exposure:
        include:
        - /*
      base-path: /