spring:
  application:
    name: zuul-server
server:
  port: 8762
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:      service-url:
      #defaultZone: http://192.168.1.6:8761/eureka,http://192.168.1.7:8761/eureka
      defaultZone: http://192.168.1.100:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include:
        - /*
      base-path: /