server:
  port: 8002
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  application:
    name: product-api
  cloud:
    config:
      enabled: true
      uri:
      - http://192.168.1.7:8000
      fail-fast: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.1.6:8761/eureka,http://192.168.1.7:8761/eureka
  instance:
    prefer-ip-address: true