spring:
  application:
    name: orderbusinessservice
server:
  port: 8004
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include:
        - hystrix.stream
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.1.100:8761/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true