# run this on another server
server:
  port: 8761
eureka:
  instance:
    hostname: ${eureka.instance.appname}
  client:
    service-url:
      defaultZone: http://192.168.1.100:8761/eureka # register peer awareness