spring:
  application:
    name: discovery-server
  profiles:
    active:
    - ${spring.profiles.active}
server:
  port: 8761
  address: 192.168.1.7
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    appname: eureka
logging:
  level:
    com:
      netflix:
        eureka: false
        discovery: false